/**
 * User Types
 */
export const PERMISSION_DENIED = "PERMISSION_DENIED";
/**
 * User
 */
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const SET_PROFILE = "SET_PROFILE";
export const REFRESH_LOGIN = "RESER_AUTH";
export const PHONE_EXISTS = "PHONE_EXISTS";
export const USER_CREATED = "USER_CREATED";
export const USERS_RECEIVED = "USERS_RECEIVED";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_OCCUPATION = "SET_OCCUPATION";
export const EDITAR_USUARIO = "EDITAR_USUARIO";
export const GUARDAR_USUARIO = "GUARDAR_USUARIO";
export const CUENTA_RECIBIDA = "CUENTA_RECIBIDA";
export const NOT_AUTH_PROVIDER = "NOT_AUTH_PROVIDER";
export const SET_PROPIEDAD_USER = "SET_PROPIEDAD_USER";
export const RESET_AUTH_PROVIDER = "RESET_AUTH_PROVIDER";
export const SET_PROPIEDAD_LOGIN = "SET_PROPIEDAD_LOGIN";
export const SET_PROPERTY_PROFILE = "SET_PROPERTY_PROFILE";
export const SET_PROPERTY_USER_DATA = "SET_PROPERTY_USER_DATA";
export const SET_PROPERTY_OCCUPATION = "SET_PROPERTY_OCCUPATION";
export const SET_CONFIRMATION_RESULT = "SET_CONFIRMATION_RESULT";
/**
 * SuperFetch
 */

export const SET_SUPER_FETCH = "SET_SUPER_FETCH";
export const SET_INPUTS = "SET_INPUTS";
export const SET_OUTPUTS = "SET_OUTPUTS";
export const SET_LOADING = "SET_LOADING";
export const SET_FEEDBACK_CHANGES = 'SET_FEEDBACK_CHANGES';
export const SET_FEEDBACK_FORM = 'SET_FEEDBACK_FORM';
export const SET_FEEDBACK = 'SET_FEEDBACK';
export const SET_SMALL_DEVICE = 'SET_SMALL_DEVICE';
export const SET_ENHANCED_PROMPT = 'SET_ENHANCED_PROMPT';

/**
 * Modal
 */
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const SET_RESPONSE = "SET_RESPONSE";
export const CLEAR = "CLEAR";
export const CLEAR_MODAL = "CLEAR_MODAL";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const MODAL_COMPONENT = "MODAL_COMPONENT";
export const SHOW_ALERT = "SHOW_ALERT";
export const SHOW_SUCCESS = "SHOW_SUCCESS";
/**
 * Spinners
 */
export const HIDE_SPINNER = "HIDE_SPINNER";
export const SHOW_SPINNER = "SHOW_SPINNER";
/**
 * Updates
 */
export const SET_UPDATED = "SET_UPDATED";
/**
 * Videos
 */
export const VIDEOS_RECIBIDOS = "VIDEOS_RECIBIDOS";
export const SINGLE_VIDEO_RECIBIDO = "SINGLE_VIDEO_RECIBIDO";
export const SET_PROPIEDAD_VIDEO = "SET_PROPIEDAD_VIDEO";
export const CLEAR_VIDEOS = "CLEAR_VIDEOS";
export const APPEND_VIDEOS = "APPEND_VIDEOS";
export const CREATE_VIDEO = "CREATE_VIDEO";
export const PURCHASE_NEEDED = "PURCHASE_NEEDED";
export const FAVORITOS_RECIBIDOS = "FAVORITOS_RECIBIDOS";
/**
 * Home
 */
export const ONLINE_HOME_RECIBIDOS = "ONLINE_HOME_RECIBIDOS";
export const PRESENCIALES_HOME_RECIBIDOS = "PRESENCIALES_HOME_RECIBIDOS";
export const ESPECIALES_HOME_RECIBIDOS = "ESPECIALES_HOME_RECIBIDOS";
/**
 * Schedule
 */
export const SET_MONTH = "SET_MONTH";
export const SET_WEEK = "SET_WEEK";
export const SEMANAS_RECIBIDAS = "SEMANAS_RECIBIDAS";
export const RESERVATIONS_RECIBIDAS = "RESERVATIONS_RECIBIDAS";
export const SET_CLASE = "SET_CLASE";
export const SET_PROPIEDAD_CLASE = "SET_PROPIEDAD_CLASE";
export const CREATE_CLASE = "CREATE_CLASE";
export const CLASS_TYPES_RECIBIDOS = "CLASS_TYPES_RECIBIDOS";
export const CLASES_RECIBIDAS = "CLASES_RECIBIDAS";
export const DISABLE_RESERVATIONS = "DISABLE_RESERVATIONS";
export const ENABLE_RESERVATIONS = "ENABLE_RESERVATIONS";
export const SET_RESERVATION = "SET_RESERVATION";
/**
 * Locations
 */
export const LOCATIONS_RECIBIDAS = "LOCATIONS_RECIBIDAS";
export const SET_LOCATION = "SET_LOCATION";
export const CREATE_LOCATION = "CREATE_LOCATION";
export const SET_PROPIEDAD_LOCATION = "SET_PROPIEDAD_LOCATION";
/**
 * Checkout
 */
export const SET_PAQUETE = "SET_PAQUETE";
export const SET_PAYMENT_SOURCE = "SET_PAYMENT_SOURCE";
/**
 * Metodos Pago
 */
export const PAYMENT_METHODS_RECIBIDOS = "PAYMENT_METHODS_RECIBIDOS";
/**
 * Favoritos
 */
export const AGREGAR_FAVORITO = "AGREGAR_FAVORITO";
export const ELIMINAR_FAVORITO = "ELIMINAR_FAVORITO";
/**
 * Class Category
 */
export const CLASS_CATEGORIES_RECIBIDAS = "CLASS_CATEGORIES_RECIBIDAS";
export const CLASS_CATEGORY_RECIBIDA = "CLASS_CATEGORY_RECIBIDA";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const SET_PROPIEDAD_CATEGORY = "SET_PROPIEDAD_CATEGORY";
/**
 * Video Type
 */
export const CLEAR_RELOAD = "CLEAR_RELOAD";
export const VIDEO_TYPE_RECIBIDOS = "VIDEO_TYPE_RECIBIDOS";
/**
 * Customers
 */
export const CUSTOMERS_RECIBIDOS = "CUSTOMERS_RECIBIDOS";
export const SET_CUSTOMER = "SET_CUSTOMER";
/**
 * Coaches
 */
export const COACHES_RECIBIDAS = "COACHES_RECIBIDAS";
export const SET_PROPIEDAD_COACH = "SET_PROPIEDAD_COACH";
export const CREATE_COACH = "CREATE_COACH";
export const SET_COACH = "SET_COACH";
/**
 * Analytics
 */
export const INGRESOS_RECIBIDOS = "INGRESOS_RECIBIDOS";
/**
 * Productos
 */
export const PRODUCTOS_RECIBIDOS = "PRODUCTOS_RECIBIDOS";
/**
 * Descuentos
 */
export const SET_DISCOUNT_CODE = "SET_DISCOUNT_CODE";
export const DESCUENTOS_RECIBIDOS = "DESCUENTOS_RECIBIDOS";
export const SET_PROPIEDAD_DESCUENTO = "SET_PROPIEDAD_DESCUENTO";
export const CREATE_DESCUENTO = "CREATE_DESCUENTO";
export const SET_DESCUENTO = "SET_DESCUENTO";
export const SHOW_SPINNER_DESCUENTO = "SHOW_SPINNER_DESCUENTO";
export const HIDE_SPINNER_DESCUENTO = "HIDE_SPINNER_DESCUENTO";
/**
 * Class Types
 */
export const SET_CLASS_TYPE = "SET_CLASS_TYPE";
export const SET_PROPIEDAD_CLASS_TYPE = "SET_PROPIEDAD_CLASS_TYPE";
export const CREATE_CLASS_TYPE = "CREATE_CLASS_TYPE";
/**
 * Filters
 */
export const SET_FILTER = "SET_FILTER";
/**
 * Programs
 */
export const SET_NONCE = "SET_NONCE";
export const SET_COMPLETED = "SET_COMPLETED";
export const PROGRAMS_RECIBIDOS = "PROGRAMS_RECIBIDOS";
/**
 * Tags Recibidos
 */
export const TAGS_RECIBIDOS = "TAGS_RECIBIDOS";

/**
 * Invoices
 */
export const SET_PROPERTY_INVOICE = "SET_PROPERTY_INVOICE";
export const INVOICES_RECEIVED = "INVOICES_RECEIVED";
export const CREATE_INVOICE = "CREATE_INVOICE";
export const CLEAR_INVOICES = "CLEAR_INVOICES";
export const SET_INVOICE = "SET_INVOICE";